// <auto-generated/>

global using global::Microsoft.EntityFrameworkCore;
global using global::Microsoft.EntityFrameworkCore.Metadata.Builders;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.Logging;
global using global::ShareMarket.Core.Constants;
global using global::ShareMarket.Core.Entities;
global using global::ShareMarket.Core.Entities.Audits;
global using global::ShareMarket.Core.Entities.Users;
global using global::ShareMarket.Core.Extensions;
